### ISSUE TITLE
Implement Github webhook receiver

### ISSUE THREAD

**Issue by vtemian** [presslabs/wordpress-operator#28]

**Comment by calind** [comment]
Issue moved to [presslabs/stack #12](https://github.com/presslabs/stack/issues/12) via [**ZenHub**](https://www.zenhub.com/)

**Comment by calind** [comment]
Issue moved to [presslabs/stack #13](https://github.com/presslabs/stack/issues/13) via [**ZenHub**](https://www.zenhub.com/)
