### ISSUE TITLE
Deploying a Wordpress Site - no POD is deployed

### ISSUE THREAD

**Issue by guillierf** [presslabs/wordpress-operator#39]
When trying to deploy a Wordpress site using the given example, I don't see any pod deployed in my K8s cluster, although 'kubectl get wordpress' shows the site:

**kubectl get wordpress**
NAME     AGE
mysite   5m17s

**kubectl get pod**
NAME                                  READY   STATUS    RESTARTS   AGE
wordpress-operator-7554fff899-4mb4v   1/1     Running   0          17m

=> no wordpress pod is created

more info:

**kubectl describe wordpress mysite**
Name:         mysite
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"wordpress.presslabs.org/v1alpha1","kind":"Wordpress","metadata":{"annotations":{},"name":"mysite","namespace":"default"},"s...
API Version:  wordpress.presslabs.org/v1alpha1
Kind:         Wordpress
Metadata:
  Creation Timestamp:  2019-08-15T17:24:10Z
  Generation:          1
  Resource Version:    357188
  Self Link:           /apis/wordpress.presslabs.org/v1alpha1/namespaces/default/wordpresses/mysite
  UID:                 7e3aef3c-bf81-11e9-8623-00505684da21
Spec:
  Bootstrap:
    Env:
      Name:  WORDPRESS_BOOTSTRAP_USER
      Value From:
        Secret Key Ref:
          Key:   USER
          Name:  mysite
      Name:      WORDPRESS_BOOTSTRAP_PASSWORD
      Value From:
        Secret Key Ref:
          Key:   PASSWORD
          Name:  mysite
  Code:
    Git:
      Repository:  https://github.com/example.com
  Domains:
    example.com
  Env:
    Name:   WORDPRESS_DB_HOST
    Value:  mysite-mysql
    Name:   WORDPRESS_DB_PASSWORD
    Value From:
      Key:             PASSWORD
      Secret Key Ref:  mysite-mysql
  Env From:
  Image:  quay.io/presslabs/wordpress-runtime
  Ingress Annotations:
  Media:
    Gcs:
      Bucket:  calins-wordpress-runtime-playground
      Env:
        Name:  GOOGLE_CREDENTIALS
        Value From:
          Secret Key Ref:
            Key:   google_application_credentials.json
            Name:  mysite
        Name:      GOOGLE_PROJECT_ID
        Value:     development
      Prefix:      mysite/
  Replicas:        3
  Tag:             latest
  Tls Secret Ref:  mysite-tls
  Volume Mounts:
  Volumes:
Events:  <none>

**Comment by vtemian** [comment]
Hello @guillierf,

Sorry for the late reply.
We've done some upgrades on the wordpress-operator and on the stack.
Can you please upgrade the operator, try again and if it still doesn't work, please attach the operator log.

**Comment by avif** [comment]
I think the issue is caused by using the example values withouth changing the "code" & "media" value,
to be clear you also need to pre-install mysql and set the "DB_*" env variables to match it.

**Comment by esteban1983cl** [comment]
I have the same issue, I attach my config:

`yaml
apiVersion: wordpress.presslabs.org/v1alpha1
kind: Wordpress
metadata:
  name: demo-site
  namespace: wordpress
spec:
  replicas: 1
  domains:
    - demosite.example.com
  # image: quay.io/presslabs/wordpress-runtime
  # tag: latest
  code: # where to find the code
    # contentSubpath: wp-content/
    # by default, code get's an empty dir. Can be one of the following:
    git:
      repository: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      reference: master
    env:
     - name: SSH_RSA_PRIVATE_KEY
       valueFrom:
         secretKeyRef:
           name: eurofashion-ecommerce-deploy-key
           key: id_rsa

    # persistentVolumeClaim: {}
    # hostPath: {}
    # emptyDir: {} (default)

  #media: # where to find the media files
    # by default, code get's an empty dir. Can be one of the following:
    #gcs: # store files using Google Cloud Storage
      #bucket: calins-wordpress-runtime-playground
      #prefix: mysite/
      #env:
        #- name: GOOGLE_CREDENTIALS
        #  valueFrom:
        #    secretKeyRef:
        #      name: mysite
        #      key: google_application_credentials.json
        #- name: GOOGLE_PROJECT_ID
        #  value: development
    # persistentVolumeClaim: {}
    # hostPath: {}
    # emptyDir: {}
  bootstrap: # wordpress install config
    env:
      - name: WORDPRESS_BOOTSTRAP_USER
        valueFrom:
          secretKeyRef:
            name: eurofashion-ecommerce-wordpress-bootstrap
            key: USERNAME
      - name: WORDPRESS_BOOTSTRAP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: eurofashion-ecommerce-wordpress-bootstrap
            key: PASSWORD
      - name: WORDPRESS_BOOTSTRAP_EMAIL
        valueFrom:
          secretKeyRef:
            name: eurofashion-ecommerce-wordpress-bootstrap
            key: EMAIL
      - name: WORDPRESS_BOOTSTRAP_TITLE
        valueFrom:
          secretKeyRef:
            name: eurofashion-ecommerce-wordpress-bootstrap
            key: TITLE
  # extra volumes for the Wordpress container
  volumes: []
  # extra volume mounts for the Wordpress container
  volumeMounts: []
  # extra env variables for the Wordpress container
  env:
    - name: DB_HOST
      value: "xxxxxxxxxxxxxxxxxxxxxxx"
    - name: DB_USER
      valueFrom:
        secretKeyRef: eurofashion-ecommerce-wordpress-database
        key: USERNAME
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef: eurofashion-ecommerce-wordpress-database
        key: PASSWORD
    - name: DB_NAME
      valueFrom:
        secretKeyRef: eurofashion-ecommerce-wordpress-database
        key: DATABASE
  envFrom: []

  # secret containg HTTPS certificate
  # tlsSecretRef: mysite-tls
  # extra ingress annotations
  ingressAnnotations:
    kubernetes.io/ingress.class: nginx-internal
`
Log from wordpress-operator

`text
E0213 20:53:14.970214       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.Wordpress: v1alpha1.WordpressList.Items: []v1alpha1.Wordpress: v1alpha1.Wordpress.Spec: v1alpha1.WordpressSpec.Env: []v1.EnvVar: v1.EnvVar.ValueFrom: v1.EnvVarSource.SecretKeyRef: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|tKeyRef":"eurofashio|..., bigger context ...|ER","valueFrom":{"key":"USERNAME","secretKeyRef":"eurofashion-ecommerce-wordpress-database"}},{"name|...
`
