### ISSUE TITLE
Support Kubernetes api version 1

### ISSUE THREAD

**Issue by datagen24** [presslabs/wordpress-operator#60]
**Is your feature request related to a problem? Please describe.**
Trying to deploy on a new cluster running K8s 1.17 this no longer has support for api version v1beta2. this has been removed since Kubernetes 1.16 

**Describe the solution you'd like**
new version/release/tag of chart with api v1

**Comment by phal0r** [comment]
Still a problem. Operator cannot be deployed in Kubernetes 1.17 and newer.

**Comment by datagen24** [comment]
Still an issue

**Comment by AMecea** [comment]
Hi @datagen24, this is fixed in `v0.9.1`. Please let me know if you encounter the error any more. Thank you!
